on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy with Password
    steps:
- name: "Checkout"
  uses: actions/checkout@v4
  with:
    fetch-depth: 0
- name: "Deploy"
  uses: milanmk/actions-file-deployer@master
  with:
    remote-protocol: "sftp"
    remote-host: ${{ secrets.FTP_SERVER }}
    remote-user: ${{ secrets.FTP_USERNAME }}
    ssh-private-key: ${{ secrets.FTP_PASSWORD }}
    remote-path: "/"
